Repository R055A/voc, pull requests merged in 2020-09, with the labels that each got.

#1 Review Math Module with Ceiling Method Implementation with Test Case
  python/common/python/math.java
Labels: good first issue

#6 Review & Merge 'Add math module TranspileTestCase test' commit to SprintOneTeamOne
  tests/stdlib/test_math.py
Labels: good first issue

#12 Review & merge ' java method for Python math.floor TDD' & tests
  python/common/python/math.java
  stdlib_tests/test_math.py
  tests/stdlib/test_math.py
Labels: good first issue

#11 Review & Merge 'Add math module TranspileTestCase test' to SprintOne
  python/common/python/math.java
  stdlib_tests/test_math.py
  tests/stdlib/test_math.py
Labels: good first issue

#17 Added Int part of floor test
  python/common/python/math.java
Labels: good first issue

#30 Add Sprint Two review rules doc
  docs/review/reviewRulesForMaintenanceGroup5.md
Labels: documentation

#44 New branch van luc
  python/common/org/python/stdlib/datetime/Date.java
  python/common/test/python/stdlib/datetime/DateTest.java
Labels: bug
